# Generated by Django 5.0.6 on 2024-07-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noise', '0003_remove_noise_result1_remove_noise_result2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noise',
            name='result1000_1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 1000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result1000_2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 1000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result1000_3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 1000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result1000_4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 1000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result125_1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 125 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result125_2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 125 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result125_3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 125 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result125_4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 125 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result2000_1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 2000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result2000_2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 2000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result2000_3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 2000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result2000_4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 2000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result250_1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 250 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result250_2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 250 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result250_3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 250 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result250_4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 250 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result31_1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 31.5 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result31_2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 31.5 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result31_3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 31.5 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result31_4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 31.5 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result4000_1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 4000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result4000_2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 4000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result4000_3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 4000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result4000_4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 4000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result500_1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 500 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result500_2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 500 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result500_3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 500 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result500_4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 500 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result63_1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 63 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result63_2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 63 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result63_3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 63 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result63_4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 63 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result8000_1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 8000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result8000_2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 8000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result8000_3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 8000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='result8000_4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Уровень звука на частоте 8000 Гц'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='resultA_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Эквтвалентный уровень звука/Уровень звука А'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='resultA_2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Эквтвалентный уровень звука/Уровень звука А'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='resultA_3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Эквтвалентный уровень звука/Уровень звука А'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='resultA_4',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Эквтвалентный уровень звука/Уровень звука А'),
        ),
    ]
