# Generated by Django 5.0.6 on 2024-07-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noise', '0005_alter_noise_result1000_1_alter_noise_result1000_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noise',
            name='resultMin',
            field=models.FloatField(verbose_name='Минимальный измеренный результат'),
        ),
    ]
